/** Report U20. Every visible string in one place.
 *
 * The interface is Swedish and there is no second locale. The point is not translation today: it is
 * that adding one becomes a data change rather than a search through 3 800 lines of JSX. Messages
 * that vary are functions rather than templates with holes, so the grammar — Swedish plurals
 * especially — lives with the text instead of at the call site.
 *
 * A second locale is an object of the same shape: `const en: typeof sv = { … }` and the compiler
 * lists everything still missing.
 *
 * Three things are deliberately not here.
 *
 * The security page and the introduction are documents, not interface strings: their paragraphs
 * carry inline markup, and cutting them into keyed fragments would need a rich-text message format
 * and would make both the code and the text worse. They are translated as documents, by replacing
 * the component.
 *
 * shortcuts.ts is already one table, where each label belongs beside the key it describes. Moving
 * only the labels here would split one thing across two files. */
/** The plan names its entity kinds in the singular, and a sentence that lists several of them needs
 * the plural. Swedish makes four different plurals out of these seven words, so the forms are written
 * down rather than derived. */
const plurals: Record<string, string> = {
  projekt: 'projekt', version: 'versioner', utkast: 'utkast', binding: 'bindings',
  profil: 'profiler', dataset: 'dataset', regel: 'regler', blocklistterm: 'blocklisttermer',
};
const plural = (kind: string) => plurals[kind] ?? kind;
const swedishList = (items: string[]) => items.length < 2 ? items.join('')
  : `${items.slice(0, -1).join(', ')} och ${items[items.length - 1]}`;
const capitalise = (text: string) => text.charAt(0).toUpperCase() + text.slice(1);

export const sv = {
  nav: {
    newCode: '＋ Ny kod',
    projects: 'Mina projekt',
    shortcuts: 'Genvägar',
    showShortcuts: 'Visa kortkommandon',
    bindings: 'Bindings',
    sanitize: 'Sanera',
    backup: 'Backup',
    security: 'Säkerhet',
    settings: 'Inställningar',
    main: 'Huvudnavigation',
    skip: 'Hoppa till innehållet',
    lock: 'Lås valvet',
  },
  vault: {
    heading: 'Kryptering',
    statePlaintext: 'Valvet ligger i klartext i webbläsarens IndexedDB. Det är standard: appen fungerar utan lösenord och ingenting kan bli oåtkomligt.',
    stateEncrypted: 'Valvet är krypterat. Varje post är låst med AES-256-GCM och nyckeln finns bara i minnet medan du är upplåst.',
    protectsNote: 'Kryptering skyddar valvet när webbläsaren är stängd eller disken hamnar i fel händer. Den skyddar inte mot ett tillägg som läser sidan medan du arbetar, mot minnet i en upplåst flik eller mot vad du själv kopierar.',
    enable: 'Kryptera valvet',
    enableTitle: 'Kryptera valvet',
    enableLead: 'Välj ett lösenord. Allt som redan finns i valvet krypteras om på en gång, och en återställningsnyckel visas en gång efteråt.',
    enableWarning: 'Tappar du både lösenordet och återställningsnyckeln finns ingen väg tillbaka. Appen har ingen kopia och kan inte hjälpa dig.',
    enableConfirm: 'Kryptera',
    encrypting: 'Krypterar…',
    enabled: 'Valvet är krypterat.',
    newPassword: 'Nytt lösenord',
    repeatPassword: 'Upprepa lösenordet',
    currentPassword: 'Nuvarande lösenord',
    password: 'Lösenord',
    passwordHint: (min: number) => `Minst ${min} tecken. Sparas ingenstans — inte ens i valvet.`,
    tooShort: (min: number) => `Lösenordet behöver minst ${min} tecken.`,
    mismatch: 'De två lösenorden är inte lika.',
    recoveryTitle: 'Din återställningsnyckel',
    recoveryLeadNew: 'Spara den här nyckeln på ett annat ställe än datorn valvet ligger på. Den öppnar valvet om lösenordet är borta, och den visas bara igen för den som kan lösenordet.',
    recoveryLeadAgain: 'Samma nyckel som när valvet krypterades. Byter du lösenord fortsätter den att fungera.',
    downloadKey: 'Ladda ner som fil',
    keptIt: 'Jag har sparat nyckeln på ett säkert ställe.',
    keyFileHeading: 'Återställningsnyckel för AI Code Vault',
    keyFileBody: 'Öppnar valvet i den här webbläsaren om lösenordet är borta. Förvara den skilt från datorn. Vem som helst med den här nyckeln kommer åt valvets privata värden.',
    changePassword: 'Byt lösenord',
    changeTitle: 'Byt lösenord',
    changeConfirm: 'Byt lösenord',
    passwordChanged: 'Lösenordet är bytt. Återställningsnyckeln fungerar som förut.',
    showRecovery: 'Visa återställningsnyckel',
    revealLead: 'Lösenordet krävs för att visa nyckeln.',
    recoveryKey: 'Återställningsnyckel',
    recoveryShape: 'En återställningsnyckel är 32 tecken, 0–9 och a–f. Bindestreck och versaler spelar ingen roll.',
    useRecovery: 'Använd återställningsnyckel i stället',
    usePassword: 'Använd lösenord i stället',
    disable: 'Stäng av kryptering',
    disableTitle: 'Stänga av kryptering?',
    disableLead: 'Allt skrivs tillbaka i klartext i den här webbläsaren, som innan valvet krypterades.',
    disableWhere: 'Lösenordet eller återställningsnyckeln krävs, eftersom det är det som bevisar att valvet är ditt.',
    disableConfirm: 'Stäng av kryptering',
    disabled: 'Krypteringen är avstängd. Valvet ligger i klartext igen.',
    autoLock: 'Lås automatiskt efter',
    autoLockNever: 'Aldrig',
    autoLockMinutes: (n: number) => `${n} minuters inaktivitet`,
    autoLockHint: 'Räknar från senaste tangenttryck eller klick. Osparad text sparas först; går det inte låses valvet inte.',
    lockNow: 'Lås nu',
    locked: 'Valvet är låst.',
    lockFailed: 'Valvet låstes inte: din text kunde inte sparas först. Den finns kvar i fliken.',
    lockedEyebrow: 'LÅST VALV',
    lockedTitle: 'Valvet är låst.',
    lockedLead: 'Ange lösenordet du valde när du krypterade valvet.',
    recoveryLead: 'Ange återställningsnyckeln du sparade när valvet krypterades.',
    lockedFootnote: 'Ingenting läses förrän valvet är öppet. Appen har ingen kopia av lösenordet och kan inte skicka det någonstans.',
    unlock: 'Lås upp',
    unlocking: 'Låser upp…',
    unlockFailed: 'Valvet kunde inte låsas upp.',
    wrongSecret: 'Fel lösenord eller återställningsnyckel.',
    failed: 'Åtgärden misslyckades.',
    exportEncrypted: 'Exportfilen krypteras med valvets lösenord.',
    importPassword: 'Filen är krypterad. Ange lösenordet eller återställningsnyckeln som gällde när den skrevs.',
    importOpen: 'Öppna filen',
    importWrong: 'Fel lösenord eller återställningsnyckel för den här filen.',
    exportPlaintextAnyway: 'Exportera i klartext ändå',
    exportPlaintextTitle: 'Exportera i klartext?',
    exportPlaintextLead: 'Valvet är krypterat, men den här filen blir det inte. Den innehåller dina privata värden i läsbar form.',
    exportPlaintextConfirm: 'Exportera i klartext',
  },
  save: {
    loading: 'Öppnar lokalt valv…',
    failed: 'Fel vid sparning',
    saved: 'Sparat lokalt',
    saving: 'Sparar lokalt…',
  },
  refusal: {
    busy: 'Något sparas just nu. Försök igen om ett ögonblick.',
    navigating: 'Sidbytet väntar tills den pågående åtgärden är klar. Försök igen om ett ögonblick.',
    settingsNotReady: 'Inställningarna är inte inlästa ännu. Försök igen om ett ögonblick.',
    bindingInLocal: 'Byt till Mall-vyn för att skapa en binding. Local är en skrivskyddad projektion.',
    bindingNoSelection: 'Markera värdet du vill binda först.',
    bindingOnPlaceholder: 'Markeringen innehåller redan en platshållare. Markera ett värde i stället.',
    noFile: 'Öppna en fil först. Det finns ingen kod att kopiera härifrån.',
    emptyFile: 'Filen är tom. Klistra in kod först.',
    copyBlocked: 'Kopiering blockerad. Åtgärda problemen i panelen — de säger vad som saknas.',
    downloadBlocked: 'Nedladdning blockerad. Åtgärda problemen i panelen — de säger vad som saknas.',
    selectionBlocked: (reason: string) => `Markeringen kan inte kopieras: ${reason}`,
    clipboardDenied: 'Webbläsaren nekade urklippsåtkomst. Kontrollera sidans behörighet.',
    unknownPage: 'Sidan finns inte. Öppna Mina projekt för att fortsätta.',
    actionFailed: 'Åtgärden kunde inte slutföras. Din text finns kvar.',
    projectListFailed: 'Projektlistan kunde inte läsas. Din kod finns kvar.',
    settingNotSaved: 'Inställningen gäller inte — den kunde inte sparas.',
  },
  workspace: {
    renameProject: 'Ändra projektnamn',
    backToCurrent: 'Tillbaka till pågående projekt',
    newProjectHint: 'Nytt projekt skapas när du börjar',
    dropHint: 'Släpp filen för att läsa in den',
    pasteHere: 'Klistra in din kod här',
    pasteHereHint: 'Projektet skapas automatiskt och sparas lokalt.',
    trySample: 'eller prova med exempelkod',
    files: (n: number) => `${n} ${n === 1 ? 'fil' : 'filer'}`,
    basedOn: (version: string) => ` · baserad på v${version}`,
    lines: (n: number) => `${n} rader`,
    bindingCount: (n: number) => `${n} bindings`,
    localFooter: 'Använd endast i din lokala kodmiljö',
    draftFooter: 'Utkast sparas automatiskt · ingen kod körs',
    bannerTemplate: '▤ MALL — KAN INNEHÅLLA KÄNSLIGA VÄRDEN',
    bannerLocal: '⚠ LOCAL — INNEHÅLLER RIKTIGA VÄRDEN',
    /** Only says sanitised when something actually was. With no bindings the AI projection is
     * byte-identical to the template, and the solid accent banner then sat above real secrets
     * telling the reader they had been dealt with. */
    bannerAi: (replaced: number) => `◇ AI — SANERAD · ${replaced === 1 ? '1 värde ersatt' : `${replaced} värden ersatta`}`,
    bannerAiNothing: '◇ AI — INGET ERSATT ÄNNU',
    editableSource: 'Redigerbar källa',
    readOnlyProjection: 'Skrivskyddad projektion',
    editAsTemplate: 'Redigera som mall',
    showValues: 'Visa värden',
    hideValues: 'Dölj värden',
    editorSettings: 'Editorinställningar',
    smallerText: 'Mindre text',
    largerText: 'Större text',
    wordWrap: (on: boolean) => `Radbrytning ${on ? 'på' : 'av'}`,
    language: 'Språk',
    fileRead: (name: string) => `${name} inläst. Inget skickas någonstans.`,
    languageSet: (language: string) => `Språket sattes till ${language}. Ändra i väljaren om det blev fel.`,
  },
  copy: {
    downloadedLocal: 'Filen är nedladdad · den innehåller riktiga värden.',
    downloaded: 'Filen är nedladdad.',
    copiedLocal: 'LOCAL kopierad · riktiga värden i urklippet',
    copiedAi: 'AI-kod kopierad',
    selectionCopied: (n: number) => `Markeringen kopierad · ${n} ${n === 1 ? 'värde' : 'värden'} utbytta.`,
    clipboardCleared: 'Urklippet är rensat.',
    clipboardReplaced: 'Urklippet innehåller något annat nu och lämnades orört.',
    clipboardStuck: 'Urklippet kunde inte rensas. Kopiera något ofarligt för att skriva över det.',
    clipboardKept: 'Urklippet lämnas kvar.',
    clearingIn: (seconds: number) => `Urklippet rensas om ${seconds} s`,
  },
  dialog: {
    attention: 'Åtgärden behöver uppmärksamhet',
    close: 'Stäng',
    closeDialog: 'Stäng dialog',
    closeNotice: 'Stäng meddelande',
    cancel: 'Avbryt',
    retrySave: 'Försök spara igen',
  },
  version: {
    labelHint: 'Valfritt, men gör historiken läsbar. Datum och antal ändrade rader visas ändå.',
    autoLabelHint: (label: string) => `Lämnas fältet tomt blir etiketten "${label}".`,
    firstLabel: (lines: number) => `${lines} rader`,
    draftBasedOnIt: 'Utkastet bygger på den här versionen. Återställ en annan först.',
    deleteTitle: (n: number) => `Radera v${n}?`,
    deleteConfirm: 'Radera versionen',
    deleteBody: (label: string) => `${label ? `"${label}"` : 'Versionen'} tas bort ur historiken för alltid.`,
    deleteDraftUnaffected: 'Utkastet du arbetar i påverkas inte.',
    deleted: (n: number) => `v${n} är raderad.`,
    replaceDraft: 'Ersätt utkastet',
    replaceDraftBody: (n: number) => `Det nuvarande arbetsutkastet ersätts av innehållet i v${n}.`,
    replaceDraftKept: 'Sparade versioner påverkas inte och går att gå tillbaka till.',
    restoredTo: (n: number) => `Återgång till v${n}`,
    restoreThis: 'Återställ den här versionen',
    restoreNumbered: (n: number) => `Återställ v${n}`,
    loadingDiff: 'Laddar jämförelsen…',
    /** The pane labels. Without them the only clue to which side is older is the arrow in the
     * title, and reading a restore the wrong way round is exactly the mistake worth preventing. */
    paneBefore: (n: number) => `v${n} · tidigare`,
    paneAfter: (n: number) => `v${n} · den här`,
    readOnlyView: (n: number) => `v${n} · skrivskyddad`,
    changedLines: (n: number) => (n === 1 ? '1 ändrad rad' : `${n} ändrade rader`),
    identical: 'Ingen skillnad i den här filen',
    /** Said when the version predates the file the workspace happens to have open. The viewer shows
     * a file the version actually contains instead of two empty panes. */
    fileNotInVersion: (name: string, n: number) => `${name} fanns inte i v${n}.`,
    showingFile: (name: string) => `Visar ${name}`,
    fileMissingBefore: (n: number) => `Filen fanns inte i v${n} — allt räknas som tillagt.`,
    ofFiles: (n: number) => `${n} filer i versionen`,
    emptyInVersion: 'Filen var tom i den här versionen.',
    pickFile: 'Fil i versionen',
    readOnlyNote: 'Skrivskyddad mall som den såg ut när versionen sparades. Ditt utkast är orört.',
    templateReplaced: 'Mallen är ersatt. Granska innan du sparar en version.',
  },
  project: {
    deleteTitle: (name: string) => `Radera ${name}?`,
    deleteConfirm: 'Radera projektet',
    deleteLead: 'Följande försvinner för alltid från den här datorn:',
    deleteVersions: (n: number) => `${n} sparade versioner`,
    deleteBindings: (n: number) => `${n} bindings som hör till projektet, med sina privata värden`,
    deleteDraft: 'Det pågående utkastet',
    deleteGlobalsSafe: 'Globala bindings påverkas inte. Exportera en backup först om du är osäker.',
    deleted: (name: string) => `${name} är raderat.`,
    detailsSaved: 'Projektuppgifterna är sparade.',
    removeFileTitle: (name: string) => `Ta bort ${name}?`,
    removeFileConfirm: 'Ta bort filen',
    removeProfileTitle: (name: string) => `Ta bort ${name}?`,
    removeProfileConfirm: 'Ta bort profilen',
    removeFileBody: 'Filens innehåll försvinner ur arbetsutkastet.',
    removeFileKept: 'Sparade versioner behåller sin kopia, så den går att få tillbaka därifrån.',
    empty: 'Inga projekt ännu. Välj Ny kod och klistra in för att börja.',
    noMatch: 'Inga projekt matchar sökningen.',
    allProjects: 'Alla projekt',
    vaultEyebrow: 'DITT LOKALA VALV',
    listLead: 'Ditt pågående arbete ligger kvar medan du letar.',
  },
  binding: {
    selectInTemplate: 'Markera värdet i Mall-vyn så att rätt förekomst kan identifieras.',
    templateChanged: 'Mallen har ändrats sedan du markerade. Ingenting sparades; markera värdet igen.',
    deleteTitle: (name: string) => `Radera ${name}?`,
    deleteConfirm: 'Radera bindingen',
    valueGone: 'Det privata värdet försvinner ur valvet.',
    noValue: 'Bindingen har inget privat värde.',
    placeholdersKept: 'Sparade versioner behåller sina platshållare.',
    deleted: (name: string) => `${name} är raderad.`,
    renamed: (from: string, to: string, n: number) => `${from} heter nu ${to}. ${n} platshållare skrevs om.`,
    defaultsUnaffected: 'Standardvärdena påverkas inte.',
  },
  app: {
    theme: 'Tema',
    themeSystem: 'System',
    themeLight: 'Ljust',
    themeDark: 'Mörkt',
    themeNotSaved: 'Temat gäller nu men kunde inte sparas.',
    offlineFailed: 'Offline-cache kunde inte aktiveras. Behåll appen öppen.',
    updateAvailable: 'Uppdatering tillgänglig',
    reload: 'Ladda om appen',
    startNow: 'BÖRJA DIREKT',
    shortcutsTitle: 'Kortkommandon',
    inTheEditor: 'I editorn',
    undone: 'Ångrat.',
    undoFailed: 'Det gick inte att ångra. Ingenting ändrades tillbaka.',
    settingsSaved: 'Inställningar sparade lokalt',
    // Said "M1" until the milestone scheme it referred to was replaced by the report's list.
    footerNote: 'Lokalt valv · ingen nätverksåtkomst',
  },
  settings: {
    eyebrow: 'DEN HÄR INSTALLATIONEN',
    title: 'Inställningar',
    lead: 'Valvet delas inte mellan olika origin eller webbläsarprofiler.',
    origin: 'Aktuellt origin',
    path: 'App-sökväg',
    deviceId: 'Enhets-ID',
    storage: 'Lagring',
    storageValue: (encrypted: boolean) => encrypted ? 'IndexedDB · krypterad med ditt lösenord' : 'IndexedDB · lokal klartext',
    persistence: 'Beständig lagring',
    persistenceReading: 'Läser…',
    persistenceUnsupported: 'Stöds inte av webbläsaren',
    persistenceYes: 'Ja · valvet vräks inte vid diskbrist',
    persistenceNo: 'Nej · webbläsaren får radera valvet',
    space: 'Utrymme',
    spaceUsed: (used: string, quota: string) => `${used} av ${quota}`,
    spaceUnknown: 'okänt',
    atRiskTitle: 'Valvet kan raderas av webbläsaren',
    atRiskBody: 'Utan beständig lagring får webbläsaren slänga valvet när enheten får ont om utrymme. Det finns ingen backup att återställa från.',
    requestPersistence: 'Begär beständig lagring',
    persistenceGranted: 'Beständig lagring beviljad.',
    persistenceDenied: 'Webbläsaren nekade beständig lagring.',
    deviceName: 'Enhetsnamn',
    includePrompt: 'Lägg en instruktion överst i AI-kopian',
    promptText: 'Instruktionens text',
    promptLabel: 'Instruktion till AI',
    promptHint: 'Kopieras som en kommentar före koden, i det språk filen har. Gör det troligare att platshållarna kommer tillbaka orörda.',
    sentinel: 'Märk Kopiera RIKTIGT med en varningsrad överst',
    sentinelHint: 'Raden säger att texten bär riktiga värden, och gör att appen känner igen en fil från din editor om den klistras in som AI-svar. Skrivs som en kommentar i filens språk, och utelämnas i språk som saknar kommentarer.',
    clearClipboard: 'Rensa urklipp efter Copy Local',
    clearNever: 'Aldrig',
    clear30: 'Efter 30 sekunder',
    clear60: 'Efter 1 minut',
    clear300: 'Efter 5 minuter',
    clearHint: 'Skriver över urklippet när tiden gått. Nedräkningen visas och går att avbryta. Urklippshistorik och molnsynk ligger utanför appens kontroll.',
    save: 'Spara inställningar',
    showIntro: 'Visa introduktionen igen',
    backupNote: 'Utkast sparas automatiskt på den här datorn. Automatisk sparning är ingen backup — exportera en fil.',
    backupHeading: 'Backup',
    backupMoved: 'Export, återställning och rensning har en egen sida:',
    backupLink: 'Backup',
  },
  bindingsPage: {
    title: 'Alla bindings',
    lead: 'Varje namn du har bundit, i vilket projekt det än hör hemma. Globala bindings finns bara här.',
    create: '＋ Ny binding',
    search: 'Sök binding',
    searchHint: 'Namn eller beskrivning',
    scope: 'Räckvidd',
    scopeAll: 'Alla',
    scopeGlobal: 'Global',
    scopeProject: 'Projekt',
    scopeVersion: 'Version',
    count: (shown: number, total: number) => `${shown} av ${total}`,
    withoutValue: (n: number) => ` · ${n} utan värde`,
    noMatch: 'Inga bindings matchar filtret.',
    empty: 'Inga bindings ännu. Markera ett värde i editorn och tryck Ctrl+B.',
    columnName: 'Namn',
    columnCategory: 'Kategori',
    columnScope: 'Räckvidd',
    columnValue: 'Privat värde',
    columnUsage: 'Används i',
    columnActions: 'Åtgärder',
    valueSet: 'Angivet',
    valueMissing: '⚠ Saknas',
    usedIn: (n: number) => `${n} ${n === 1 ? 'version' : 'versioner'}`,
    ownerGlobal: 'Alla projekt',
    ownerDeletedProject: 'Raderat projekt',
    ownerDeletedVersion: 'Raderad version',
    ownerUnknown: 'Okänt projekt',
    edit: (name: string) => `Redigera ${name}`,
    remove: (name: string) => `Radera ${name}`,
  },
  undo: {
    action: 'Ångra',
    close: 'Stäng ångra-remsan',
    seconds: (n: number) => `${n} s`,
  },
  toolbar: {
    views: 'Kodvy',
    template: 'Mall',
    local: 'Local',
    ai: 'AI',
    ingest: 'Klistra in från AI ↙',
    copySelection: 'Kopiera markering ↗',
    blockedCount: (n: number) => `${n} problem hindrar kopiering — se panelen`,
    blockedBy: (n: number, view: string) => `Blockerad: ${n} problem i ${view}-vyn`,
  },
  exits: {
    copyAi: 'Kopiera för AI',
    problems: (n: number) => `${n} problem`,
    findings: (n: number) => `${n} fynd att granska`,
    downloadAi: 'Spara AI-kopia som fil',
    copyLocal: 'Kopiera RIKTIGT',
    copyLocalArmed: 'Kopiera RIKTIGT · tryck igen',
    armedHint: 'Nästa tryck lägger riktiga värden i urklippet. Armeringen släpper av sig själv efter fem sekunder.',
    details: 'Visa detaljer',
    checkResolved: (done: number, total: number) => `${done} av ${total} bindings har ett värde`,
    checkMissing: (names: string[]) => `Värde saknas: ${names.join(', ')}`,
    checkBlocked: (n: number) => `${n} ${n === 1 ? 'kontext' : 'kontexter'} går inte att escapa säkert`,
    checkSecrets: (n: number) => (n === 1 ? '1 riktigt värde skrivs in i klartext' : `${n} riktiga värden skrivs in i klartext`),
    checkProfile: (name: string) => `Värdena kommer från profilen ${name}`,
    checkDefaultProfile: 'Ingen profil är vald · standardvärdena används',
    checkClipboard: 'Urklippshistorik och molnsynk ligger utanför appens kontroll.',
    copiedAi: (n: number) => `AI-kod kopierad · ${n === 1 ? '1 värde ersatt' : `${n} värden ersatta`}`,
  },
  clipboardBanner: {
    counting: (s: number) => `Riktiga värden i urklippet · rensas om ${s} s`,
    held: 'Riktiga värden i urklippet',
    pending: 'Urklippet kunde inte rensas — riktiga värden ligger kvar.',
    clearNow: 'Rensa nu',
    retry: 'Försök igen',
    keep: 'Avbryt',
    historyNote: 'Urklippshistorik (Win+V) och molnsynkat urklipp nås inte från en webbsida.',
  },
  files: {
    tabs: 'Filer i projektet',
    name: 'Filnamn',
    renameHint: 'Dubbelklicka för att byta namn',
    remove: (name: string) => `Ta bort ${name}`,
    add: 'Lägg till fil',
  },
  review: {
    needsReview: 'Granskning krävs',
    suspicious: (n: number) => `${n} misstänkta värden hittades`,
    nothingToProtect: 'Ingenting att skydda hittades i koden',
    nothingProtected: 'Inga värden är skyddade',
    clean: 'Inga kända problem hittades',
    boundOf: (bound: number, literals: number) => `${bound} av ${literals}`,
    coverageTail: (replaced: number) => ` strängvärden är kopplade till bindings. ${replaced} förekomster ersätts vid kopiering.`,
    nothingBound: 'Inget värde är kopplat till en binding, så allt nedan skickas som det står.',
    finding: (line: number, rule: string) => `rad ${line} · ${rule} · `,
    andMore: (n: number) => `och ${n} till`,
    scopeListed: 'de misstänkta värden som listas ovan',
    scopeScan: 'en genomsökning efter misstänkta värden',
    scopeNote: (scope: string) => `Kontrollen omfattar saknade bindings, stödd escaping, exakta kända privata värden och ${scope}. Mönstren fångar det som liknar hemligheter — inte allt som är känsligt i just din miljö. Läs igenom koden själv innan du delar den.`,
    localTitle: '⚠ Kopiera riktiga värden',
    aiTitle: 'AI-export · granska före kopiering',
    localWarning: 'Den lokala koden innehåller secrets. Kopiera den endast till din lokala kodmiljö, aldrig till en AI-chatt.',
    localProfile: (name: string) => `Värdena kommer från profilen ${name}. Bindings utan eget värde där använder standardvärdet.`,
    localDefaultProfile: 'Värdena är standardvärdena. Ingen profil är vald.',
    localClipboardNote: 'Urklippshistorik och molnsynk kan lagra eller överföra innehållet. Appen kontrollerar inte dessa funktioner.',
    acknowledge: (n: number) => `Jag har tittat på de ${n} misstänkta värdena och vill ändå kopiera.`,
    download: 'Ladda ned som fil',
    copyLocalConfirm: 'Kopiera LOCAL med secrets',
    copyAiReviewed: 'Jag har granskat · kopiera för AI',
    copyAnyway: 'Kopiera oskyddad kod ändå',
  },
  bindingDialog: {
    acknowledgeFirst: 'Bekräfta att AI-värdet är granskat innan du sparar.',
    saveFailed: 'Bindingen kunde inte sparas. Ändringarna finns kvar i dialogen.',
    name: 'Namn',
    nameLabel: 'Bindingnamn',
    renameNote: 'Platshållaren skrivs om i alla versioner och utkast som använder den.',
    reuseLead: (name: string) => `Värdet ligger redan i valvet som ${name}.`,
    reuseAction: (name: string) => `Använd {{${name}}}`,
    category: 'Kategori',
    scope: 'Scope',
    scopeProject: 'Projekt',
    scopeGlobal: 'Globalt',
    scopeVersion: 'Version',
    aiValue: 'AI-värde',
    aiSees: 'AI:n ser ',
    more: '▸ Fler val · AI-värde, räckvidd, profiler',
    fewer: '▾ Färre val',
    defaultValue: 'Privat värde · standard',
    profileValue: (profile: string) => `Privat värde för ${profile}`,
    showValue: 'Visa privat värde',
    emptyMeansDefault: 'Tomt betyder att standardvärdet används.',
    raw: 'Raw · ingen escaping',
    rawNote: 'Raw stänger av escaping. Värdet läggs in ordagrant och kan ändra kodens syntax och betydelse.',
    description: 'Beskrivning',
    vagueBefore: 'AI-värdet ser inte ut som en tydlig platshållare, till exempel ',
    vagueAfter: '. Jag har granskat att det är ofarligt att dela.',
    replaceAll: (n: number) => n === 1
      ? 'Ersätt även den andra identiska förekomsten i filen'
      : `Ersätt även de ${n} andra identiska förekomsterna i filen`,
    lead: 'Ange privata värden utan kodens escaping. Endast AI-värdet visas i den sanerade vyn.',
    rootLead: (root: string) => `Sökvägen ligger under din rot ${root}. Skriv den mot roten så följer den med om du flyttar arbetsmappen.`,
    rootUse: 'Skriv mot roten',
    rootTemplate: 'Skrivs mot roten: ',
    rootResolves: (path: string) => `Blir ${path} på den här datorn.`,
    rootDrop: 'Använd en fast sökväg i stället',
    sharedAi: (name: string) => `AI-värdet används redan av ${name}. Två bindings med samma AI-värde går inte att skilja åt när koden kommer tillbaka från AI:n.`,
    saving: 'Sparar…',
    save: 'Spara binding',
  },
  projectList: {
    sortBy: 'Sortera',
    sortUpdated: 'Senast ändrade',
    sortCreated: 'Senast skapade',
    sortName: 'Namn',
    search: 'Sök i alla projekt',
    searchHint: 'Sök namn, tagg eller filnamn…',
    filterLanguage: 'Filtrera på språk',
    filterStatus: 'Filtrera på status',
    current: 'Pågående →',
    open: 'Öppna →',
    fileCount: (n: number) => `${n} ${n === 1 ? 'fil' : 'filer'}`,
  },
  drawer: {
    close: 'Stäng projektpanelen',
    search: 'Sök projekt',
    searchHint: 'Namn, tagg eller filnamn',
    currentPrefix: 'Pågående · ',
    noMatch: 'Inga projekt matchar sökningen.',
    empty: 'Dina projekt visas här när du har klistrat in kod.',
    seeAll: 'Visa alla projekt →',
    title: 'Mina projekt',
  },
  bindingPanel: {
    title: 'Bindings',
    used: 'En binding används',
    hasValue: 'Privat värde angivet',
    missingValue: '⚠ VÄRDE SAKNAS',
    occurrences: (n: number) => `${n} ${n === 1 ? 'förekomst' : 'förekomster'}`,
    empty: 'Dina privata värden får en egen plats här.',
  },
  severity: {
    critical: 'Kritisk',
    high: 'Hög',
    medium: 'Medel',
    low: 'Låg',
  },
  rules: {
    ownTerm: 'Ett sökord du själv lagt till.',
    termAdded: 'Sökordet är tillagt.',
    literalNote: 'Matchas ordagrant, oavsett stora eller små bokstäver. Reguljära uttryck stöds inte.',
  },
  findings: {
    selectAll: 'Markera alla',
    choose: (rule: string, line: number) => `Välj ${rule} på rad ${line}`,
    bindChosen: (count: number) => count === 0 ? 'Skapa bindings'
      : count === 1 ? 'Skapa binding för den valda'
      : `Skapa ${count} bindings`,
    boundMany: (count: number) => `${count} bindings skapade. Värdena är utbytta mot platshållare.`,
    boundManyUndo: (count: number) => `${count} bindings skapade från granskningsfynden.`,
    reused: (name: string) => `Värdet är utbytt mot {{${name}}}.`,
    title: 'Misstänkta värden',
    dismissed: (rule: string) => `${rule} är avfärdad i det här projektet.`,
  },
  candidates: {
    fromPaste: (n: number) => (n === 1 ? 'Hittade 1 värde i det du klistrade in' : `Hittade ${n} värden i det du klistrade in`),
    elsewhere: 'Övriga i filen',
    none: 'Inga kandidater i den här filen.',
    lead: 'Förslag, inte fynd. Ingen av dem blockerar kopiering — du avgör vad som är känsligt. De förkryssade har raden själv pekat ut.',
    create: 'Skapa…',
    useExisting: (name: string) => `Använd {{${name}}}`,
    dismiss: 'Ofarligt här',
    jump: (rule: string, line: number) => `Visa ${rule} på rad ${line} i koden`,
  },
  category: {
    secret: 'Hemlighet',
    identity: 'Identitet',
    infrastructure: 'Infrastruktur',
    environment: 'Miljö',
    configuration: 'Konfiguration',
    testdata: 'Testdata',
  },
  sanitize: {
    title: 'Sanera text',
    eyebrow: 'UTAN ATT SPARA',
    lead: 'Klistra in ett felmeddelande, ett transcript eller utdata från ett kommando. Kända riktiga värden byts mot sina AI-värden, blocklistan tillämpas och resten granskas. Ingenting sparas.',
    input: 'Text att sanera',
    inputHint: 'Klistra in här',
    output: 'Saniterad text',
    replaced: (n: number) => (n === 1 ? '1 känt värde utbytt' : `${n} kända värden utbytta`),
    nothingReplaced: 'Inga kända värden i texten.',
    copy: 'Kopiera för AI',
    copied: 'Saniterad text kopierad.',
    empty: 'Klistra in något att sanera först.',
    blocked: (n: number) => `${n} ${n === 1 ? 'känt riktigt värde finns' : 'kända riktiga värden finns'} kvar i texten. Bind ${n === 1 ? 'det' : 'dem'} först.`,
    bindNow: 'Bind nu',
    hide: 'Dölj',
    clear: 'Rensa',
    findings: 'Ser ut som känsliga värden',
    findingsLead: 'Inget av det här är känt för valvet. Bind det som är riktigt, så byts det ut här och i alla projekt.',
  },
  ingest: {
    tier1: 'Platshållare kvar',
    tier2: 'Återställd',
    tier3: 'Liknar — granska själv',
    title: 'Klistra in kod från AI',
    pasteHere: 'Klistra in svaret här',
    codeLabel: 'Kod från AI',
    summary: (applied: number, suggestions: number) => `${applied} platshållare på plats, ${suggestions} att granska`,
    fromEditor: 'Den här texten ser ut att komma från din editor: den bär raden som Kopiera RIKTIGT lägger överst. Den har alltså aldrig varit sanerad.',
    exposedTitle: (n: number) => n === 1 ? 'Ett riktigt värde står i texten' : `${n} riktiga värden står i texten`,
    exposedLead: 'Bindingarna märks som exponerade när du ersätter mallen. Har koden varit hos en AI bör värdena bytas.',
    replacesTemplate: 'Den öppna filens mall ersätts. Spara en version först om du vill kunna gå tillbaka.',
    replace: 'Ersätt mallen',
    replaceAnyway: 'Ersätt mallen ändå',
    lostTitle: (count: number) => count === 1 ? 'En platshållare försvinner' : `${count} platshållare försvinner`,
    lostItem: (name: string, occurrences: number) =>
      `${name} — ${occurrences} ${occurrences === 1 ? 'förekomst' : 'förekomster'} i mallen, ingen i den nya koden`,
    lostLead:
      'Där platshållaren stod står nu något annat. Ersätter du mallen är värdet inte längre skyddat, och nästa Copy for AI skickar det som står där i stället.',
  },
  backup: {
    privateExported: 'Privata värden exporterade.',
    exportFailed: 'Exporten misslyckades. Inget har ändrats.',
    fileUnreadable: 'Filen kunde inte läsas.',
    importDone: 'Importen är klar.',
    importFailed: 'Importen misslyckades. Valvet är oförändrat.',
    clearHeading: 'Rensa',
    clearIntro:
      'Tar bort allt som hör till den här appen i den här webbläsaren: valvet, temavalet och den offline-kopia av appen som ligger i webbläsarens cache. Använd det innan du lämnar en delad dator, och exportera först om något ska sparas.',
    clearButton: 'Rensa hela valvet',
    clearTitle: 'Rensa hela valvet?',
    clearConfirm: 'Rensa valvet',
    clearProjects: (count: number) => `${count} projekt med all versionshistorik`,
    clearBindings: (count: number) => `${count} ${count === 1 ? 'binding' : 'bindings'}, med sina privata värden`,
    clearBrowser: 'Temavalet, avregistrering av service workern och dess cachade kopia av appen',
    clearNotCovered:
      'Det här ligger utanför: filer du redan exporterat, det som ligger i urklippet, och samma app på en annan adress, i en annan webbläsare eller på en annan dator.',
    clearLead: 'Allt på den här datorn raderas för alltid:',
    clearNoUndo: 'Det finns ingen ångra. Exportera en backup först om du kan behöva något av det igen.',
    cleared: 'Valvet är rensat.',
    plaintextWarning: 'Båda filerna innehåller dina riktiga värden i klartext.',
    neverExported: 'Valvet har aldrig exporterats. En fil är den enda vägen tillbaka om webbläsardata rensas.',
    lastExport: (days: number) => days === 0 ? 'Senast exporterat i dag.'
      : days === 1 ? 'Senast exporterat i går.'
      : `Senast exporterat för ${days} dagar sedan.`,
    restore: 'Återställ',
    fileRejected: 'Filen kunde inte användas',
    replacedElsewhere: 'Valvet har bytts ut under den öppna sessionen. Ladda om innan du arbetar vidare.',
    planTitle: 'Så här skulle importen se ut',
    blocked: 'Importen är blockerad',
    keepBoth: 'Behåll båda — importera som kopia',
    keepVault: 'Behåll det som finns i valvet',
    takeFile: 'Ta filens version',
    onConflict: 'Vid krock',
    applyMerge: 'Slå ihop med valvet',
    applyReplace: 'Ersätt valvet med filen',
    /** Only a project and a binding can be imported as a copy; the rest are pointed at by id or
     * numbered within their project, so a second copy would refer to the wrong thing. The kinds
     * come from the plan, so the sentence names exactly the ones this file would hit. */
    keepBothLimited: (kinds: string[]) =>
      `Behåll båda gäller projekt och bindings. ${capitalise(swedishList(kinds.map(plural)))} kan inte importeras som kopior — där behålls valvets version.`,
    replaceMode: 'Ersätt hela valvet med filen i stället för att slå ihop',
    replaceUnavailable:
      'Filen innehåller bara privata värden. Att ersätta valvet med den skulle radera projekt, versioner och utkast utan att lägga tillbaka något, så ersätt-läget gäller bara en full export.',
    replaceWarning:
      'Valvet töms först. Allt som inte finns i filen är borta efteråt, och inga krockar uppstår eftersom ingenting finns kvar att krocka med.',
    replaceTitle: 'Ersätta hela valvet?',
    replaceConfirm: 'Ersätt valvet',
    replaceLead: 'Valvet töms och fylls med filens innehåll:',
    replaceProjects: (now: number, incoming: number) =>
      `${now} projekt i valvet raderas, ${incoming} kommer från filen`,
    replaceBindings: (now: number, incoming: number) =>
      `${now} ${now === 1 ? 'binding' : 'bindings'} i valvet raderas, ${incoming} kommer från filen`,
  },
  blocklist: {
    heading: 'Blocklista',
    lead: 'Termer som aldrig får nå en AI. De byts mot en platshållare direkt när text klistras in eller en fil öppnas — till skillnad från granskningsreglerna, som pekar ut och låter dig avgöra. Bindingen blir global, eftersom beslutet gäller hela valvet och inte ett projekt.',
    termLabel: 'Term',
    termHint: 'Matchas ordagrant och skiftlägesokänsligt, vid ordgräns. Inga reguljära uttryck.',
    /** Deliberately not "AI-värde", which is the binding dialog's own field: Playwright's getByLabel
     * matches substrings, and two controls whose names contain one another are a test that fails
     * somewhere else entirely. */
    replacementLabel: 'Vad AI:n ser (valfritt)',
    replacementHint: 'Vad en AI får se i stället. Lämnas det tomt väljs ett ofarligt standardvärde för kategorin.',
    defaultReplacement: 'standardvärde',
    add: 'Lägg till term',
    added: (term: string) => `${term} läggs nu undan automatiskt.`,
    duplicate: 'Termen finns redan i listan.',
    remove: (term: string) => `Ta bort ${term}`,
    enabledLabel: (term: string) => `${term} aktiv`,
    fromTerm: (term: string) => `Från blocklistan: ${term}`,
    replaced: (count: number, terms: number) =>
      `${count} ${count === 1 ? 'förekomst' : 'förekomster'} av ${terms} ${terms === 1 ? 'term' : 'termer'} i blocklistan byttes mot platshållare.`,
    undoLabel: (count: number) => `${count} ${count === 1 ? 'förekomst' : 'förekomster'} från blocklistan är utbytta.`,
    failed: 'Termerna i blocklistan kunde inte bytas ut. Texten står kvar som den klistrades in.',
  },
  versionPanel: {
    title: 'Versioner',
    draftBasedOnThis: ' · utkastet bygger på den här',
    empty: 'Utkastet sparas automatiskt. Spara en version när du vill kunna komma tillbaka hit.',
  },
  details: {
    descriptionHint: 'Vad gör den här koden?',
    tagsHint: 'Kommaseparerade. Sökningen i Alla projekt matchar mot dem.',
  },
  profiles: {
    empty: 'Inga profiler ännu. Standard används för alla värden.',
  },
  issues: {
    blocksBoth: 'blockerar båda kopieringarna',
    blocksAi: 'blockerar Kopiera för AI',
    blocksLocal: 'blockerar Kopiera RIKTIGT',
    replaceWith: (name: string) => `Byt mot {{${name}}}`,
    replaced: (name: string, count: number) =>
      `${count} ${count === 1 ? 'förekomst' : 'förekomster'} av värdet bakom ${name} byttes mot platshållaren.`,
    replaceUndo: (name: string) => `Värdet bakom ${name} är utbytt mot platshållaren.`,
  },
  common: {
    line: (n: number) => `rad ${n}`,
  },
  paths: {
    copyNewItem: 'Kopiera New-Item-rad',
    newItemCopied: 'New-Item-raden är kopierad · den innehåller din riktiga rot',
    root: 'Rot för arbetsmappar',
    rootHint: 'Sökvägar som skrivs mot roten följer med när du ändrar den här. Bindingar med fast sökväg rörs inte.',
    rootMoved: (n: number) => `Roten är ändrad. ${n} ${n === 1 ? 'binding följde' : 'bindingar följde'} med.`,
  },
  exposure: {
    flag: (date: string) => `Exponerad ${date}`,
    explain: 'Ett riktigt värde för den här bindingen fanns i kod som klistrades in som AI-svar.',
    rotate: 'Markera roterad',
    rotated: (name: string) => `${name} är markerad som roterad. Det gamla värdet bevakas fortfarande.`,
    rotateHint: 'Byt värdet först. Markeringen betyder att du gjort det, inte att appen kontrollerat det.',
  },
  chip: {
    reveal: 'Visa riktigt värde',
    hidesIn: (s: number) => `döljs om ${s} s`,
    noValue: 'Privat värde saknas.',
    edit: 'Redigera',
    unbind: 'Ta bort platshållaren',
    unbound: (name: string) => `Platshållaren {{${name}}} är borttagen och värdet står i filen igen.`,
    unboundUndo: (name: string) => `{{${name}}} är borttagen ur filen.`,
  },
  editorHover: {
    bindingNoValue: 'binding · värde saknas',
    valueSet: 'Privat värde är angivet.',
    valueMissing: '⚠ Privat värde saknas.',
    noBinding: '⚠ Ingen binding med det här namnet.',
  },
  controller: {
    untitled: 'Namnlöst projekt',
    needsOneFile: 'Ett projekt måste ha minst en fil.',
    saveFailed: 'Lokal sparning misslyckades. Din text finns kvar i fliken. Försök igen eller kopiera mallen till en lokal fil innan du lämnar sidan.',
    projectGone: 'Projektet finns inte längre.',
  },
} as const;

export const t = sv;
