export function Security() {
  return <article className="document"><span className="eyebrow">SÄKERHET OCH BEGRÄNSNINGAR</span><h1>Dina värden stannar i webbläsarens lokala valv.</h1>
    <p>AI Code Vault håller isär kodmallar, privata värden och AI-exempel. Appen har ingen AI-integration och kör aldrig din kod. Du väljer själv vad du kopierar.</p>
    <h2>Det här är verktyget byggt för</h2><ul><li>Minska risken att riktiga värden av misstag följer med till en AI-tjänst.</li><li>Behålla lokala värden när koden uppdateras.</li><li>Separera privata värden från delbara projekt, och ta ut en backup som går att återställa.</li></ul>
    <h2>Det här skyddar verktyget inte mot</h2><ul><li>Skadlig kod, keyloggers eller någon med tillgång till samma OS-konto.</li><li>Webbläsartillägg: de kan läsa sidans innehåll och IndexedDB.</li><li>Urklippshistorik och molnsynkat urklipp. Copy Local lägger riktiga värden i urklippet; automatisk rensning når bara urklippet självt.</li><li>Diskforensik: privata värden lagras i klartext i IndexedDB.</li><li>Att någon manuellt skriver privata värden i en AI-chatt.</li><li>Att den publicerade GitHub Pages-appen komprometteras.</li></ul>
    <h2>Begränsade kontroller, ingen garanti</h2><p>Före AI-kopiering kontrolleras saknade bindings, stödda strängkontexter och exakta kända privata värden, och du får se hur många av kodens strängvärden som faktiskt är skyddade. Appen letar ännu inte på egen hand efter hemligheter den inte känner till. Okända känsliga värden kan finnas kvar. Granska alltid texten.</p>
    <p>Appens CSP blockerar sidans anslutnings-API:er. Ett byggtest söker efter nätverksanrop i JavaScript-bundlen. Dessa kontroller ersätter inte granskning av appen eller dess beroenden.</p>
    <h2>Lagring och offline</h2><p>GitHub levererar appfilerna. Projekt och privata värden lagras lokalt i webbläsaren och skickas inte till GitHub av appen. Efter första lyckade cachelagringen fungerar appen offline. Uppdateringskontrollen hämtar endast appfiler.</p>
    <p>Appen sparar också ditt temaval i localStorage, enbart för att första bilden efter en omladdning inte ska blinka i fel färg. Valvet är bundet till origin och webbläsarprofil. Localhost och GitHub Pages har separata data. Olika repo-sökvägar på samma GitHub Pages-domän har samma origin: de är inte säkerhetsisolerade från varandra. Välj ett primärt origin.</p>
    <p className="notice">Rensad webbläsardata kan inte återställas av appen. Exportera valvet från inställningarna och förvara filen som du förvarar värdena den innehåller — även den privata exporten är klartext.</p>
  </article>;
}
