export function Security() {
  return <article className="document"><span className="eyebrow">SÄKERHET OCH BEGRÄNSNINGAR</span><h1>Dina värden stannar i webbläsarens lokala valv.</h1>
    <p>AI Code Vault håller isär kodmallar, privata värden och AI-exempel. Appen har ingen AI-integration och kör aldrig din kod. Du väljer själv vad du kopierar.</p>
    <h2>Det här är verktyget byggt för</h2><ul><li>Minska risken att riktiga värden av misstag följer med till en AI-tjänst.</li><li>Behålla lokala värden när koden uppdateras.</li><li>Separera privata värden från delbara projekt, och ta ut en backup som går att återställa.</li></ul>
    <h2>Det här skyddar verktyget inte mot</h2><ul><li>Skadlig kod, keyloggers eller någon med tillgång till samma OS-konto.</li><li>Webbläsartillägg: de kan läsa sidans innehåll och IndexedDB.</li><li>Urklippshistorik och molnsynkat urklipp. Copy Local lägger riktiga värden i urklippet; automatisk rensning når bara urklippet självt.</li><li>Ett upplåst valv: medan du arbetar finns nyckeln i minnet och värdena i sidan.</li><li>Att någon manuellt skriver privata värden i en AI-chatt.</li><li>Att den publicerade GitHub Pages-appen komprometteras.</li></ul>
    <h2>Begränsade kontroller, ingen garanti</h2><p>Före AI-kopiering kontrolleras saknade bindings, stödda strängkontexter och exakta kända privata värden, och du får se hur många av kodens strängvärden som faktiskt är skyddade. En heuristisk scanner pekar dessutom ut värden som <em>liknar</em> hemligheter, men den varnar bara — heuristik hårdblockerar aldrig, eftersom falska positiva som inte går att kvittera leder till att verktyget kringgås. Okända och omskrivna värden kan finnas kvar. Granska alltid texten.</p>
    <p>Blocklistan är en lista du själv fyller i, inte ett skydd som hittar termer åt dig. Termer du lägger till byts mot en platshållare när text klistras in eller en fil öppnas — ordagrant, skiftlägesokänsligt och vid ordgräns. Den ser inte stavfel, förkortningar, sammansättningar eller en term som skrivits isär, och den rör inte text som redan ligger i arbetsytan. Ersättningen visas och går att ångra i ett steg.</p>
    <p>Appens CSP blockerar sidans anslutnings-API:er. Ett byggtest söker efter nätverksanrop i JavaScript-bundlen. Dessa kontroller ersätter inte granskning av appen eller dess beroenden.</p>
    <h2>Kryptering är valbar</h2><p>Som standard ligger valvet i klartext i IndexedDB. Det är ett val: ett valv utan lösenord kan inte bli oåtkomligt. Slår du på kryptering under Inställningar packas en slumpad datanyckel in med ditt lösenord (PBKDF2-SHA256, 600 000 varv) och varje post krypteras med AES-256-GCM. Id:n och tidsstämplar ligger kvar i klartext, eftersom databasen måste kunna hitta en rad utan nyckeln — det som syns utan lösenord är att ett projekt finns och när det ändrades, aldrig vad det innehåller.</p>
    <p>Nyckeln finns bara i minnet medan valvet är upplåst. Låst valv visar en låsskärm och ingenting annat. Krypteringen skyddar alltså disken och den stängda webbläsaren, inte ett tillägg som läser sidan medan du arbetar och inte det du själv kopierar. En återställningsnyckel visas en gång när valvet krypteras: tappar du både den och lösenordet finns ingen väg tillbaka, och appen har ingen kopia av något av dem. Är valvet krypterat krypteras exportfilen med samma lösenord.</p>
    <h2>Lagring och offline</h2><p>GitHub levererar appfilerna. Projekt och privata värden lagras lokalt i webbläsaren och skickas inte till GitHub av appen. Efter första lyckade cachelagringen fungerar appen offline. Uppdateringskontrollen hämtar endast appfiler.</p>
    <p>Appen sparar också ditt temaval i localStorage, enbart för att första bilden efter en omladdning inte ska blinka i fel färg. "Rensa hela valvet" tar bort det tillsammans med valvet, service workern och den cachade kopian av appen. Valvet är bundet till origin och webbläsarprofil. Localhost och GitHub Pages har separata data. Olika repo-sökvägar på samma GitHub Pages-domän har samma origin: de är inte säkerhetsisolerade från varandra. Välj ett primärt origin.</p>
    <p className="notice">Rensad webbläsardata kan inte återställas av appen. Exportera valvet från backupsidan och förvara filen som du förvarar värdena den innehåller — från ett okrypterat valv är även den privata exporten klartext.</p>
  </article>;
}
