#!/usr/bin/env node
/**
 * Dependency hygiene check.
 *
 * 1. Every production dependency (from package-lock.json) must have an
 *    allow-listed license and must not look like analytics/telemetry.
 * 2. Writes THIRD-PARTY-NOTICES.md for the production dependency tree.
 *
 * Exit code 1 on any violation.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const root = resolve(new URL('..', import.meta.url).pathname)
const lock = JSON.parse(readFileSync(join(root, 'package-lock.json'), 'utf8'))

const LICENSE_ALLOW = new Set([
  'MIT',
  'ISC',
  'BSD-2-Clause',
  'BSD-3-Clause',
  'Apache-2.0',
  '0BSD',
  'Unlicense',
  'CC0-1.0',
  '(MIT OR Apache-2.0)',
  '(MIT OR CC0-1.0)',
  'MIT OR Apache-2.0',
])

const NAME_DENY = /analytics|telemetry|sentry|posthog|mixpanel|amplitude|segment\.io|bugsnag|datadog|newrelic|hotjar|tracking/i

const problems = []
const notices = []

for (const [key, pkg] of Object.entries(lock.packages ?? {})) {
  if (key === '' || pkg.dev) continue
  const name = key.replace(/^.*node_modules\//, '')
  if (NAME_DENY.test(name)) {
    problems.push(`Dependency name looks like telemetry/analytics: ${name}`)
  }
  let license = pkg.license
  let homepage = ''
  let licenseText = ''
  const dir = join(root, key)
  try {
    const meta = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'))
    license = license ?? (typeof meta.license === 'string' ? meta.license : meta.license?.type)
    homepage = meta.homepage ?? (typeof meta.repository === 'string' ? meta.repository : (meta.repository?.url ?? ''))
    const licenseFile = readdirSync(dir).find((f) => /^licen[cs]e/i.test(f))
    if (licenseFile) licenseText = readFileSync(join(dir, licenseFile), 'utf8')
  } catch {
    // package dir missing: license from lock only
  }
  if (!license || !LICENSE_ALLOW.has(license)) {
    problems.push(`License not allow-listed for ${name}@${pkg.version}: ${license ?? 'unknown'}`)
  }
  notices.push({ name, version: pkg.version, license: license ?? 'unknown', homepage, licenseText })
}

notices.sort((a, b) => a.name.localeCompare(b.name))
const out = [
  '# Third-party notices',
  '',
  'CodeVault bundles the following open-source packages. Generated by `npm run check-deps`.',
  '',
  ...notices.map((n) => `- ${n.name}@${n.version} — ${n.license}${n.homepage ? ` — ${n.homepage}` : ''}`),
  '',
  '---',
  '',
  ...notices.flatMap((n) => [
    `## ${n.name}@${n.version}`,
    '',
    n.licenseText.trim() || `License: ${n.license} (no license file in package)`,
    '',
  ]),
]
writeFileSync(join(root, 'THIRD-PARTY-NOTICES.md'), out.join('\n'))

console.log(`Checked ${notices.length} production packages.`)
if (problems.length) {
  console.error('\ncheck-deps FAILED:')
  for (const p of problems) console.error(' - ' + p)
  process.exit(1)
}
console.log('check-deps OK: no telemetry names, all licenses allow-listed. THIRD-PARTY-NOTICES.md written.')
